---
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pyright:
    name: Run pyright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry
      - run: poetry install
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - name: Run pyright
        uses: jakebailey/pyright-action@v2.3.0
